apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-with-env-deployment
  labels:
    app: webapp-with-env
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp-with-env
  template:
    metadata:
      labels:
        app: webapp-with-env
    spec:
      containers:
        - name: webapp-with-env
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env-config-v1
